services:
  app_proxy:
    environment:
      APP_HOST: denny-siyuan_app_1
      APP_PORT: 6806
      PROXY_AUTH_ADD: "false"

  app:
    image: b3log/siyuan:latest
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 6806 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=umbrel']
    security_opt:
      - no-new-privileges:true
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/siyuan/workspace:rw
